prompts = [
    "What are the benefits of learning a new language?",
    "How does technology impact education?",
    "What are the effects of climate change on wildlife?",
    "How can we reduce plastic waste in our daily lives?",
    "What are the key factors in maintaining a healthy lifestyle?",
    "How does social media influence public opinion?",
    "What are the challenges of space exploration?",
    "How can renewable energy sources be more widely adopted?",
    "What are the psychological effects of prolonged isolation?",
    "How does art influence culture and society?",
    "What are the benefits of a plant-based diet?",
    "How can we improve mental health awareness?",
    "What are the causes and effects of global warming?",
    "How does music affect our emotions?",
    "What are the advantages of remote work?",
    "How can we promote gender equality in the workplace?",
    "What are the impacts of deforestation on the environment?",
    "How does exercise benefit mental health?",
    "What are the ethical considerations of artificial intelligence?",
    "How can we support local businesses?",
    "What are the benefits of meditation and mindfulness?",
    "How does the internet affect our attention span?",
    "What are the challenges of urbanization?",
    "How can we make education more accessible?",
    "What are the effects of pollution on human health?",
    "How does literature reflect society?",
    "What are the benefits of volunteering?",
    "How can we address the issue of homelessness?",
    "What are the impacts of fast fashion on the environment?",
    "How does globalization affect local cultures?",
    "What are the benefits of lifelong learning?",
    "How can we reduce food waste?",
    "What are the effects of screen time on children?",
    "How does architecture influence our daily lives?",
    "What are the challenges of aging populations?",
    "How can we promote sustainable tourism?",
    "What are the benefits of outdoor activities?",
    "How does the media shape our perceptions?",
    "What are the impacts of genetic engineering?",
    "How can we improve public transportation?",
    "What are the benefits of a diverse workplace?",
    "How does climate change affect agriculture?",
    "What are the challenges of cybersecurity?",
    "How can we encourage civic engagement?",
    "What are the effects of noise pollution?",
    "How does fashion influence identity?",
    "What are the benefits of team sports?",
    "How can we protect endangered species?",
    "What are the impacts of automation on jobs?",
    "How does education affect economic growth?",
    "What are the benefits of cultural exchange programs?",
    "How can we reduce our carbon footprint?",
    "What are the effects of stress on the body?",
    "How does technology affect our sleep patterns?",
    "What are the challenges of water scarcity?",
    "How can we promote healthy eating habits?",
    "What are the benefits of reading books?",
    "How does urban planning affect quality of life?",
    "What are the impacts of social inequality?",
    "How can we support mental health in schools?",
    "What are the effects of overfishing on marine life?",
    "How does travel broaden our perspectives?",
    "What are the benefits of creative hobbies?",
    "How can we address the digital divide?",
    "What are the impacts of climate change on agriculture?",
    "How does technology influence communication?",
    "What are the benefits of physical fitness?",
    "How can we promote environmental conservation?",
    "What are the effects of air pollution on health?",
    "How does culture influence our values?",
    "What are the challenges of renewable energy?",
    "How can we improve disaster preparedness?",
    "What are the benefits of studying history?",
    "How does technology impact job markets?",
    "What are the effects of poverty on education?",
    "How can we promote global cooperation?",
    "What are the benefits of sustainable living?",
    "How does art therapy benefit mental health?",
    "What are the challenges of healthcare access?",
    "How can we reduce our reliance on fossil fuels?",
    "What are the impacts of climate change on weather patterns?",
    "How does technology affect human relationships?",
    "What are the benefits of community gardens?",
    "How can we address the issue of plastic pollution?",
    "What are the effects of climate change on biodiversity?",
    "How does education influence social mobility?",
    "What are the benefits of digital literacy?",
    "How can we promote mental health in the workplace?",
    "What are the impacts of climate change on coastal areas?",
    "How does technology affect our privacy?",
    "What are the benefits of public libraries?",
    "How can we support sustainable agriculture?",
    "What are the effects of climate change on water resources?",
    "How does technology influence our daily lives?",
    "What are the benefits of renewable energy?",
    "How can we promote healthy lifestyles?",
    "What are the impacts of climate change on human health?",
    "How does technology affect education?",
    "What are the benefits of lifelong learning?",
    "How can we reduce our environmental impact?",
    "What are the effects of climate change on ecosystems?",
    "How does technology influence our work-life balance?",
    "What are the benefits of mindfulness meditation?",
    "How can we promote sustainable development?",
    "What are the impacts of climate change on food security?",
    "How does technology affect our mental health?",
    "What are the benefits of physical activity?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on weather patterns?",
    "How does technology influence our social interactions?",
    "What are the benefits of a balanced diet?",
    "How can we promote environmental sustainability?",
    "What are the impacts of climate change on wildlife?",
    "How does technology affect our daily routines?",
    "What are the benefits of regular exercise?",
    "How can we reduce our carbon emissions?",
    "What are the effects of climate change on agriculture?",
    "How does technology influence our health?",
    "What are the benefits of a healthy diet?",
    "How can we promote renewable energy?",
    "What are the impacts of climate change on water resources?",
    "How does technology affect our sleep?",
    "What are the benefits of staying active?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on biodiversity?",
    "How does technology influence our productivity?",
    "What are the benefits of a healthy lifestyle?",
    "How can we promote environmental awareness?",
    "What are the impacts of climate change on human health?",
    "How does technology affect our communication?",
    "What are the benefits of regular physical activity?",
    "How can we reduce our environmental footprint?",
    "What are the effects of climate change on ecosystems?",
    "How does technology influence our daily habits?",
    "What are the benefits of a nutritious diet?",
    "How can we promote sustainable living?",
    "What are the impacts of climate change on weather patterns?",
    "How does technology affect our relationships?",
    "What are the benefits of staying fit?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on agriculture?",
    "How does technology influence our mental health?",
    "What are the benefits of a balanced lifestyle?",
    "How can we promote environmental conservation?",
    "What are the impacts of climate change on wildlife?",
    "How does technology affect our daily lives?",
    "What are the benefits of regular exercise?",
    "How can we reduce our carbon footprint?",
    "What are the effects of climate change on water resources?",
    "How does technology influence our health?",
    "What are the benefits of a healthy diet?",
    "How can we promote renewable energy?",
    "What are the impacts of climate change on ecosystems?",
    "How does technology affect our sleep patterns?",
    "What are the benefits of staying active?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on biodiversity?",
    "How does technology influence our productivity?",
    "What are the benefits of a healthy lifestyle?",
    "How can we promote environmental awareness?",
    "What are the impacts of climate change on human health?",
    "How does technology affect our communication?",
    "What are the benefits of regular physical activity?",
    "How can we reduce our environmental footprint?",
    "What are the effects of climate change on ecosystems?",
    "How does technology influence our daily habits?",
    "What are the benefits of a nutritious diet?",
    "How can we promote sustainable living?",
    "What are the impacts of climate change on weather patterns?",
    "How does technology affect our relationships?",
    "What are the benefits of staying fit?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on agriculture?",
    "How does technology influence our mental health?",
    "What are the benefits of a balanced lifestyle?",
    "How can we promote environmental conservation?",
    "What are the impacts of climate change on wildlife?",
    "How does technology affect our daily lives?",
    "What are the benefits of regular exercise?",
    "How can we reduce our carbon footprint?",
    "What are the effects of climate change on water resources?",
    "How does technology influence our health?",
    "What are the benefits of a healthy diet?",
    "How can we promote renewable energy?",
    "What are the impacts of climate change on ecosystems?",
    "How does technology affect our sleep patterns?",
    "What are the benefits of staying active?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on biodiversity?",
    "How does technology influence our productivity?",
    "What are the benefits of a healthy lifestyle?",
    "How can we promote environmental awareness?",
    "What are the impacts of climate change on human health?",
    "How does technology affect our communication?",
    "What are the benefits of regular physical activity?",
    "How can we reduce our environmental footprint?",
    "What are the effects of climate change on ecosystems?",
    "How does technology influence our daily habits?",
    "What are the benefits of a nutritious diet?",
    "How can we promote sustainable living?",
    "What are the impacts of climate change on weather patterns?",
    "How does technology affect our relationships?",
    "What are the benefits of staying fit?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on agriculture?",
    "How does technology influence our mental health?",
    "What are the benefits of a balanced lifestyle?",
    "How can we promote environmental conservation?",
    "What are the impacts of climate change on wildlife?",
    "How does technology affect our daily lives?",
    "What are the benefits of regular exercise?",
    "How can we reduce our carbon footprint?",
    "What are the effects of climate change on water resources?",
    "How does technology influence our health?",
    "What are the benefits of a healthy diet?",
    "How can we promote renewable energy?",
    "What are the impacts of climate change on ecosystems?",
    "How does technology affect our sleep patterns?",
    "What are the benefits of staying active?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on biodiversity?",
    "How does technology influence our productivity?",
    "What are the benefits of a healthy lifestyle?",
    "How can we promote environmental awareness?",
    "What are the impacts of climate change on human health?",
    "How does technology affect our communication?",
    "What are the benefits of regular physical activity?",
    "How can we reduce our environmental footprint?",
    "What are the effects of climate change on ecosystems?",
    "How does technology influence our daily habits?",
    "What are the benefits of a nutritious diet?",
    "How can we promote sustainable living?",
    "What are the impacts of climate change on weather patterns?",
    "How does technology affect our relationships?",
    "What are the benefits of staying fit?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on agriculture?",
    "How does technology influence our mental health?",
    "What are the benefits of a balanced lifestyle?",
    "How can we promote environmental conservation?",
    "What are the impacts of climate change on wildlife?",
    "How does technology affect our daily lives?",
    "What are the benefits of regular exercise?",
    "How can we reduce our carbon footprint?",
    "What are the effects of climate change on water resources?",
    "How does technology influence our health?",
    "What are the benefits of a healthy diet?",
    "How can we promote renewable energy?",
    "What are the impacts of climate change on ecosystems?",
    "How does technology affect our sleep patterns?",
    "What are the benefits of staying active?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on biodiversity?",
    "How does technology influence our productivity?",
    "What are the benefits of a healthy lifestyle?",
    "How can we promote environmental awareness?",
    "What are the impacts of climate change on human health?",
    "How does technology affect our communication?",
    "What are the benefits of regular physical activity?",
    "How can we reduce our environmental footprint?",
    "What are the effects of climate change on ecosystems?",
    "How does technology influence our daily habits?",
    "What are the benefits of a nutritious diet?",
    "How can we promote sustainable living?",
    "What are the impacts of climate change on weather patterns?",
    "How does technology affect our relationships?",
    "What are the benefits of staying fit?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on agriculture?",
    "How does technology influence our mental health?",
    "What are the benefits of a balanced lifestyle?",
    "How can we promote environmental conservation?",
    "What are the impacts of climate change on wildlife?",
    "How does technology affect our daily lives?",
    "What are the benefits of regular exercise?",
    "How can we reduce our carbon footprint?",
    "What are the effects of climate change on water resources?",
    "How does technology influence our health?",
    "What are the benefits of a healthy diet?",
    "How can we promote renewable energy?",
    "What are the impacts of climate change on ecosystems?",
    "How does technology affect our sleep patterns?",
    "What are the benefits of staying active?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on biodiversity?",
    "How does technology influence our productivity?",
    "What are the benefits of a healthy lifestyle?",
    "How can we promote environmental awareness?",
    "What are the impacts of climate change on human health?",
    "How does technology affect our communication?",
    "What are the benefits of regular physical activity?",
    "How can we reduce our environmental footprint?",
    "What are the effects of climate change on ecosystems?",
    "How does technology influence our daily habits?",
    "What are the benefits of a nutritious diet?",
    "How can we promote sustainable living?",
    "What are the impacts of climate change on weather patterns?",
    "How does technology affect our relationships?",
    "What are the benefits of staying fit?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on agriculture?",
    "How does technology influence our mental health?",
    "What are the benefits of a balanced lifestyle?",
    "How can we promote environmental conservation?",
    "What are the impacts of climate change on wildlife?",
    "How does technology affect our daily lives?",
    "What are the benefits of regular exercise?",
    "How can we reduce our carbon footprint?",
    "What are the effects of climate change on water resources?",
    "How does technology influence our health?",
    "What are the benefits of a healthy diet?",
    "How can we promote renewable energy?",
    "What are the impacts of climate change on ecosystems?",
    "How does technology affect our sleep patterns?",
    "What are the benefits of staying active?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on biodiversity?",
    "How does technology influence our productivity?",
    "What are the benefits of a healthy lifestyle?",
    "How can we promote environmental awareness?",
    "What are the impacts of climate change on human health?",
    "How does technology affect our communication?",
    "What are the benefits of regular physical activity?",
    "How can we reduce our environmental footprint?",
    "What are the effects of climate change on ecosystems?",
    "How does technology influence our daily habits?",
    "What are the benefits of a nutritious diet?",
    "How can we promote sustainable living?",
    "What are the impacts of climate change on weather patterns?",
    "How does technology affect our relationships?",
    "What are the benefits of staying fit?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on agriculture?",
    "How does technology influence our mental health?",
    "What are the benefits of a balanced lifestyle?",
    "How can we promote environmental conservation?",
    "What are the impacts of climate change on wildlife?",
    "How does technology affect our daily lives?",
    "What are the benefits of regular exercise?",
    "How can we reduce our carbon footprint?",
    "What are the effects of climate change on water resources?",
    "How does technology influence our health?",
    "What are the benefits of a healthy diet?",
    "How can we promote renewable energy?",
    "What are the impacts of climate change on ecosystems?",
    "How does technology affect our sleep patterns?",
    "What are the benefits of staying active?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on biodiversity?",
    "How does technology influence our productivity?",
    "What are the benefits of a healthy lifestyle?",
    "How can we promote environmental awareness?",
    "What are the impacts of climate change on human health?",
    "How does technology affect our communication?",
    "What are the benefits of regular physical activity?",
    "How can we reduce our environmental footprint?",
    "What are the effects of climate change on ecosystems?",
    "How does technology influence our daily habits?",
    "What are the benefits of a nutritious diet?",
    "How can we promote sustainable living?",
    "What are the impacts of climate change on weather patterns?",
    "How does technology affect our relationships?",
    "What are the benefits of staying fit?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on agriculture?",
    "How does technology influence our mental health?",
    "What are the benefits of a balanced lifestyle?",
    "How can we promote environmental conservation?",
    "What are the impacts of climate change on wildlife?",
    "How does technology affect our daily lives?",
    "What are the benefits of regular exercise?",
    "How can we reduce our carbon footprint?",
    "What are the effects of climate change on water resources?",
    "How does technology influence our health?",
    "What are the benefits of a healthy diet?",
    "How can we promote renewable energy?",
    "What are the impacts of climate change on ecosystems?",
    "How does technology affect our sleep patterns?",
    "What are the benefits of staying active?",
    "How can we address the issue of climate change?",
    "What are the effects of climate change on biodiversity?",
    "How does technology influence our productivity?",
    "What are the benefits of a healthy lifestyle?",
    "How can we promote environmental awareness?",
    "What are the impacts of climate change on human health?",
]
